version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - patient_network

  patient-service:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/patientdb
    networks:
      - patient_network

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.test
    container_name: patient-service-tests
    depends_on:
      - patient-service
      - mongo
    networks:
      - patient_network
    volumes:
      - ./target/surefire-reports:/app/target/surefire-reports

networks:
  patient_network:

volumes:
  mongo-data:
